/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fa8ea949-645e-466b-a01b-3738d486503b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ziS5XgkJF",
    "aws_user_pools_web_client_id": "5auj9i05d96kj0jep1diclo3tt",
    "oauth": {}
};


export default awsmobile;
