/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fa8ea949-645e-466b-a01b-3738d486503b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ziS5XgkJF",
    "aws_user_pools_web_client_id": "5auj9i05d96kj0jep1diclo3tt",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://x25yhzwhfbdhbdep77nm2obc7i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-q3cgjxmzrzbufm7wy2shdmzk6e",
    "aws_user_files_s3_bucket": "amplify-app-bucket154635-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
